spring.application.name=dindin

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

# Configurações para o data.sql rodar após o Hibernate criar as tabelas
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Configuração para o jsessionid parar de apaarecer na url
server.servlet.session.tracking-modes=cookie
